### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by brianorwhatever**
added "module" type to package.json

### CODE REVIEW

**Comment by dlongley** [comment]
@davidlehn, can you say whether / how this will break existing deployments?

**Comment by brianorwhatever** [comment]
For context:

Without this in the package.json my tooling blows up with 

> Cannot use import statement outside a module

Alternatively to these PRs being merged in, maybe someone knows how I can fix this without patching the package.json and we can add instructions to the readme?

The same goes for https://github.com/credential-handler/credential-handler-polyfill/pull/31 and https://github.com/credential-handler/web-credential-handler/pull/7

**Comment by davidlehn** [comment]
- At some point we should modernize this project to our current package style.  Update directory structure and run a linter and so on.
- I imagine we're only using this in webpack flows right now, and that tooling is smart enough to do the right thing with the ESM code.  I don't think there is CJS code here that would cause an issue?
- I think in the case here, and the way this is likely used, that adding the module flag would be fine and is more correct.  It's not present only because the code here predates that flag existing.
- It wouldn't be too difficult to test by picking a project that uses this, make the change in the installed code, and make sure the webpack or other build process still works.
- At this point I just assume that typescript and react native users will experience horrible failures with or without this change, if they haven't already forked the repo. :-)
- I am in favor of this change, and I know we have a similar issue in a number of other packages (beyond the couple related PRs here).  We need to fix them all at some point to just be proper ESM first modules.

@brianorwhatever: out of curiosity, what tooling is failing?

**Comment by brianorwhatever** [comment]
@davidlehn I am using sveltekit which uses vite for bundling and optimizing dependencies. It converts cjs packages to esm and I even found a flag to convert "mixed" packages that contain both cjs and esm into purely esm. I was shocked it blew up on this with what seems like no path forward especially since the necessary change is so trivial

**Comment by brianorwhatever** [comment]
FYI @BigBlueHat

**Comment by BigBlueHat** [comment]
We need to understand what breaks here across the ecosystem as we need to be working to reduce forks--especially for a shift in module formats which we otherwise support in our code.

My key concern is that we want to bridge the module format divide and support CommonJS, ESM modules, and `<script>` tag consumption. Other projects do it...we should too since these modules have that wide of a scope.

**Pull request closed without merging**
